/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jni_Main */

#ifndef _Included_jni_Main
#define _Included_jni_Main
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jni_Main
 * Method:    test
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jni_Main_test
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
